<?php

/**
 * @file
 * Contains erpw_user_workflow_history.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function erpw_user_workflow_history_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the erpw_user_workflow_history module.
    case 'help.page.erpw_user_workflow_history':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Helps to store the records of user workflow.') . '</p>';
      return $output;

    default:
  }
}
