elements: |
  location:
    '#location_options__title': 'Select Country BN'
    '#location_tid__title': ''
    '#attached__title': ''
  step_1_add_service_details:
    '#title': 'Step 1: Add Service Details BN'
  organisation:
    '#title': 'Organisation BN'
  erpw_workflow:
    '#description': "<br />\r\n<quillbot-extension-portal></quillbot-extension-portal>"
    '#more': "<br />\r\n<quillbot-extension-portal></quillbot-extension-portal>"
    '#admin_notes': "<br />\r\n<quillbot-extension-portal></quillbot-extension-portal>"
