display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        type:
          label: Tipo
        timestamp:
          label: Fecha
        message:
          label: Message
        name:
          label: Usuario
          separator: ', '
        link:
          label: Operaciones
      filters:
        type:
          expose:
            label: Tipo
  page:
    display_title: Página
