label: 'Need Help View Sp'
display:
  default:
    display_options:
      title: 'Necesitas ayuda'
      fields:
        nothing:
          label: 'Habla a'
        field_email_id:
          label: 'Identificación de correo'
        field_telephone_number:
          label: 'Número de teléfono'
        nothing_1:
          label: 'Redes sociales'
        field_service_provider_name:
          label: 'nombre de la organización'
        field_description:
          label: Descripción
      header:
        area_text_custom:
          content: '<b>Estás seleccionando ciudad del país</b>'
      pager:
        options:
          tags:
            next: 'Próximo ›'
            previous: '‹ Previo'
            first: '« Primero'
            last: 'Último »'
