display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Anterior'
            next: 'Siguiente >'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        filename:
          label: Nombre
          separator: ', '
        filemime:
          label: 'Tipo MIME'
        status:
          label: Estado
      filters:
        filemime:
          expose:
            label: 'Tipo MIME'
        status:
          expose:
            label: Estado
  page_2:
    display_options:
      pager:
        options:
          tags:
            previous: '‹ Anterior'
            next: 'Siguiente >'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        entity_label:
          label: Entity
        type:
          label: 'Tipo de entidad'
        count:
          format_plural_string: !!binary MQNAY291bnQ=
      arguments:
        fid:
          exception:
            title: Todo(s)
