display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        name:
          label: 'Nombre de usuario'
        status:
          label: Estado
          settings:
            format_custom_true: Activo
        operations:
          label: Operaciones
      filters:
        status:
          group_info:
            label: Estado
            group_items:
              1:
                title: Activo
  page_2:
    display_options:
      filters:
        status:
          group_info:
            label: Estado
            group_items:
              1:
                title: Activo
