display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        info:
          label: 'Block description'
        type:
          label: 'Block type'
        operations:
          label: Operaciones
      filters:
        info:
          expose:
            label: 'Block description'
        type:
          expose:
            label: 'Block type'
  page_1:
    display_title: Página
