display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        title:
          label: Título
        type:
          label: 'Tipo de contenido'
        name:
          label: Autor
        operations:
          label: Operaciones
      filters:
        title:
          expose:
            label: Título
        type:
          expose:
            label: 'Tipo de contenido'
        langcode:
          expose:
            label: Idioma
