label: 'Comentarios recientes'
description: 'Comentarios recientes.'
display:
  default:
    display_title: Master
    display_options:
      title: 'Comentarios recientes'
  block_1:
    display_title: Bloque
    display_options:
      block_description: 'Comentarios recientes'
      block_category: 'Listas (Views)'
