label: Búsqueda
display:
  default:
    display_options:
      title: búsqueda
      use_more_text: 'Carga más'
      header:
        result:
          content: 'TODOS LOS RESULTADOS (@total)'
      exposed_form:
        options: {  }
      pager:
        options:
          views_infinite_scroll:
            button_text: 'Ver más'
