display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      fields:
        title:
          label: Título
        name:
          label: Autor
        status:
          label: Estado
        operations:
          label: Operaciones
      filters:
        status:
          expose:
            label: Estado
        type:
          expose:
            label: Tipo
        title:
          expose:
            label: Título
        langcode:
          expose:
            label: Idioma
    display_title: Máster
  page_1:
    display_options:
      menu:
        title: Contenido
      tab_options:
        title: Contenido
      filters:
        status:
          expose:
            label: Estado
        type:
          expose:
            label: Tipo
        title:
          expose:
            label: Título
        langcode:
          expose:
            label: Idioma
      title: Contenido
  page_2:
    display_options:
      filters:
        status:
          expose:
            label: Estado
        type:
          expose:
            label: Tipo
        title:
          expose:
            label: Título
        langcode:
          expose:
            label: Idioma
