display:
  default:
    display_options:
      empty:
        area:
          content:
            format: basic_html
            value: "<p>Users haven't viewed anything yet.</p>\r\n"
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          tags:
            previous: '‹ Anterior'
            next: 'Siguiente >'
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        title:
          label: Título
    display_title: Máster
  page:
    display_title: Página
