display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        filename:
          label: Nombre
        filemime:
          label: 'Tipo MIME'
        status:
          label: Estado
      filters:
        filemime:
          expose:
            label: 'Tipo MIME'
        status:
          expose:
            label: Estado
  page_2:
    display_options:
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      fields:
        type:
          label: 'Tipo de entidad'
