display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Search
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
      fields:
        title:
          separator: ', '
        body:
          separator: ', '
        type:
          label: Tipo
          separator: ', '
      filters:
        search_api_fulltext:
          expose:
            label: Search
      title: Search
  page:
    display_options:
      menu:
        title: Search
