_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
ignored_config_entities:
  - block.block.rpw_cta_buttons_on_homepage
  - 'google_*'
  - block.block.pendingcountservicesblock
  - email_tfa.settings
  - block.block.pendingapproval
  - block.block.views_block__user_count_approval_block_block_2
  - domain.location.*
  - user.mail
  - shield.settings
