definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  user__page:
    enabled: true
    menu_name: account
    parent: ''
    expanded: false
    weight: -49
  user__logout:
    enabled: true
    menu_name: account
    parent: ''
    weight: -44
    expanded: false
_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
