definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  user__page:
    weight: -49
    menu_name: account
    parent: ''
    enabled: false
    expanded: false
  user__logout:
    weight: -44
    menu_name: account
    parent: ''
    expanded: false
    enabled: false
_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
