_core:
  default_config_hash: 5p2lzpRAbNnhbgkvO2MKkxtc2QOBeMRkWubKyc7HYFE
node_title_validation_config:
  comma-article: 0
  exclude-article: ''
  min-article: '1'
  max-article: '255'
  min-wc-article: '1'
  max-wc-article: '25'
  unique-article: 0
  comma-organisation: 0
  exclude-organisation: ''
  min-organisation: '1'
  max-organisation: '144'
  min-wc-organisation: '1'
  max-wc-organisation: '25'
  unique-organisation: 1
  comma-page: 0
  exclude-page: ''
  min-page: '1'
  max-page: '255'
  min-wc-page: '1'
  max-wc-page: '25'
  unique-page: 0
  comma-service_type: 0
  exclude-service_type: ''
  min-service_type: '1'
  max-service_type: '255'
  min-wc-service_type: '1'
  max-wc-service_type: '25'
  unique-service_type: 0
  unique: 0
