strict: 0
non_hierarchical_roles:
  administrator: 0
  super_admin: 0
  country_admin: 0
  interagency_gbv_coordinator: 0
  service_provider_focal_point: 0
  service_provider_staff: 0
  authenticated: 0
  anonymous: 0
