interval: 60000
active_on:
  content_entity_forms: true
  config_entity_forms: false
notification:
  active: true
  message: 'Saving draft...'
  delay: 5000
allowed_content_entity_types:
  node:
    bundles:
      article: article
      page: page
_core:
  default_config_hash: QnLi3Y7e5T_v9EZqYxRb90E0bBDb2g1y7xREWLKJLC0
only_on_form_change: false
