_core:
  default_config_hash: j-ZIPT_JseG1aLxuAdzS-NomYUmBK3OUOjP53Pg8uA8
timeout: 1800
max_timeout: 172800
padding: 60
no_individual_logout_threshold: true
role_logout: false
role_logout_max: false
redirect_url: /user/login
no_dialog: false
message: 'Your session is about to expire. Do you want to reset it?'
inactivity_message: 'You have been logged out due to inactivity.'
inactivity_message_type: warning
enforce_admin: false
jstimer_format: '%hours%:%mins%:%secs%'
jstimer_js_load_option: false
use_alt_logout_method: false
use_watchdog: true
dialog_title: 'Virtualsafespace Alert'
disable_buttons: false
yes_button: 'Please keep me logged in !'
no_button: 'Yes, I understand I will be logged out !'
whitelisted_ip_addresses: ''
