_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
definitions:
  system__admin_content:
    menu_name: admin
    parent: system.admin
    weight: -99
    expanded: false
    enabled: true
  system__admin_structure:
    menu_name: admin
    parent: system.admin
    weight: -97
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:entity__block_content_type__collection':
    menu_name: admin
    parent: block.admin_display
    weight: 1
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:entity__block_content__collection':
    menu_name: admin
    parent: block.admin_display
    weight: 3
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:entity__comment__field_ui_fieldscomment':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.comment_type.edit_form.comment'
    weight: 3
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:entity__entity_form_display__comment__defaultcomment':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.comment_type.edit_form.comment'
    weight: 4
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:entity__entity_view_display__comment__default__comment':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.comment_type.edit_form.comment'
    weight: 5
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:entity__comment_type__devel_load__comment':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.comment_type.edit_form.comment'
    weight: 6
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:entity__comment_type__delete_form__comment':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.comment_type.edit_form.comment'
    weight: 7
    expanded: false
    enabled: true
  system__themes_page:
    menu_name: admin
    parent: system.admin
    weight: -96
    expanded: false
    enabled: true
  system__modules_list:
    menu_name: admin
    parent: system.admin
    weight: -95
    expanded: false
    enabled: true
  system__admin_config:
    menu_name: admin
    parent: system.admin
    weight: -94
    expanded: false
    enabled: true
  entity__user__collection:
    menu_name: admin
    parent: system.admin
    weight: -93
    expanded: false
    enabled: true
  system__admin_reports:
    menu_name: admin
    parent: system.admin
    weight: -92
    expanded: false
    enabled: true
  help__main:
    menu_name: admin
    parent: system.admin
    weight: -91
    expanded: false
    enabled: true
  comment__admin:
    menu_name: admin
    parent: system.admin_content
    weight: 1
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:view__files':
    menu_name: admin
    parent: system.admin_content
    weight: 2
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:media_page':
    menu_name: admin
    parent: system.admin_content
    weight: 3
    expanded: false
    enabled: true
  domain_content__content_list:
    menu_name: admin
    parent: system.admin_content
    weight: 4
    expanded: false
    enabled: true
  domain_content__editors_list:
    menu_name: admin
    parent: system.admin_content
    weight: 5
    expanded: false
    enabled: true
  paragraphs_library__paragraphs_library_item__collection:
    menu_name: admin
    parent: system.admin_content
    weight: 6
    expanded: false
    enabled: true
