_core:
  default_config_hash: yOPH6uEZYRHbg2OFP-bze0jGr06fI-Gr_66W-vA8Faw
langcode: es
report-only:
  enable: true
  directives:
    object-src:
      base: none
    script-src:
      base: self
      flags:
        - unsafe-inline
      sources:
        - 'https://www.googletagmanager.com'
        - 'https://cdn.jsdelivr.net'
    script-src-attr:
      base: self
    script-src-elem:
      base: self
      flags:
        - unsafe-inline
      sources:
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
        - 'https://cdn.jsdelivr.net'
    style-src:
      base: self
      flags:
        - unsafe-inline
      sources:
        - 'https://cdn.jsdelivr.net'
    style-src-attr:
      base: self
      flags:
        - unsafe-inline
      sources:
        - 'https://cdn.jsdelivr.net'
    style-src-elem:
      base: self
      flags:
        - unsafe-inline
      sources:
        - 'https://cdn.jsdelivr.net'
    frame-ancestors:
      base: self
  reporting:
    plugin: none
enforce:
  enable: true
  directives:
    default-src:
      base: self
      sources:
        - 'blob:'
    connect-src:
      base: self
      sources:
        - 'http://stage.virtualsafespace.net'
        - 'http://stage.iq.virtualsafespace.net'
        - 'http://stage.ec.virtualsafespace.net'
        - 'http://dev.virtualsafespace.net'
        - 'http://dev.iq.virtualsafespace.net'
        - 'http://dev.ec.virtualsafespace.net'
        - 'https://iq.virtualsafespace.net'
        - 'https://ec.virtualsafespace.net'
        - 'https://virtualsafespace.net'
        - 'https://bam.nr-data.net'
        - 'https://www.google-analytics.com'
        - 'https://metrics.articulate.com'
        - '*.virtualsafespace.net'
        - 'https://api.opencagedata.com'
    font-src:
      base: self
      sources:
        - 'data:'
        - 'http://stage.virtualsafespace.net'
        - 'http://stage.iq.virtualsafespace.net'
        - 'http://stage.ec.virtualsafespace.net'
        - 'http://dev.virtualsafespace.net'
        - 'http://dev.iq.virtualsafespace.net'
        - 'http://dev.ec.virtualsafespace.net'
        - 'https://iq.virtualsafespace.net'
        - 'https://ec.virtualsafespace.net'
        - 'https://virtualsafespace.net'
        - 'https://themes.googleusercontent.com'
        - 'https://fonts.gstatic.com'
        - 'https://cdn.jsdelivr.net'
        - 'https://cdnjs.cloudflare.com'
        - '*.virtualsafespace.net'
        - 'https://www.youtube.com'
        - 'https://www.vimeo.com'
        - 'https://i.ytimg.com'
    frame-src:
      base: self
      sources:
        - 'http://stage.virtualsafespace.net'
        - 'http://stage.iq.virtualsafespace.net'
        - 'http://stage.ec.virtualsafespace.net'
        - 'http://dev.virtualsafespace.net'
        - 'http://dev.iq.virtualsafespace.net'
        - 'http://dev.ec.virtualsafespace.net'
        - 'https://www.youtube.com'
        - 'https://www.vimeo.com'
        - 'https://player.vimeo.com'
        - 'https://iq.virtualsafespace.net'
        - 'https://ec.virtualsafespace.net'
        - 'https://virtualsafespace.net'
        - '*.virtualsafespace.net'
    img-src:
      base: self
      sources:
        - 'data:'
        - 'http://stage.virtualsafespace.net'
        - 'http://stage.iq.virtualsafespace.net'
        - 'http://stage.ec.virtualsafespace.net'
        - 'http://dev.virtualsafespace.net'
        - 'http://dev.iq.virtualsafespace.net'
        - 'http://dev.ec.virtualsafespace.net'
        - 'https://iq.virtualsafespace.net'
        - 'https://ec.virtualsafespace.net'
        - 'https://virtualsafespace.net'
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
        - 'https://h5p.org'
        - 'https://www.gstatic.com'
        - 'https://www.youtube.com'
        - 'https://www.vimeo.com'
        - 'https://i.ytimg.com'
    object-src:
      base: none
    script-src:
      base: self
      flags:
        - unsafe-inline
        - unsafe-eval
      sources:
        - 'https://bam.nr-data.net'
        - 'https://cdn.ampproject.org'
        - 'https://www.google-analytics.com'
        - 'https://cdnjs.cloudflare.com'
        - 'https://ajax.googleapis.com'
        - 'https://code.jquery.com'
        - 'https://cdn.jsdelivr.net'
        - 'https://www.youtube.com'
        - 'https://www.googletagmanager.com'
        - 'https://js-agent.newrelic.com'
        - 'https://www.vimeo.com'
    script-src-elem:
      base: self
      flags:
        - unsafe-inline
      sources:
        - 'https://cdn.jsdelivr.net'
        - 'https://www.googletagmanager.com'
        - 'https://www.google-analytics.com'
    style-src:
      base: self
      flags:
        - unsafe-inline
        - unsafe-eval
      sources:
        - 'http://stage.virtualsafespace.net'
        - 'http://stage.iq.virtualsafespace.net'
        - 'http://stage.ec.virtualsafespace.net'
        - 'http://dev.virtualsafespace.net'
        - 'http://dev.iq.virtualsafespace.net'
        - 'http://dev.ec.virtualsafespace.net'
        - 'https://iq.virtualsafespace.net'
        - 'https://ec.virtualsafespace.net'
        - 'https://virtualsafespace.net'
        - 'https://fonts.googleapis.com'
        - '*.virtualsafespace.net'
        - 'https://translate.googleapis.com'
        - 'https://cdn.jsdelivr.net'
        - 'https://cdnjs.cloudflare.com'
        - 'https://www.youtube.com'
        - 'https://www.vimeo.com'
        - 'https://i.ytimg.com'
    style-src-elem:
      base: self
      flags:
        - unsafe-inline
      sources:
        - 'https://cdn.jsdelivr.net'
    worker-src:
      base: self
      sources:
        - 'blob:'
    frame-ancestors:
      base: self
    upgrade-insecure-requests: true
  reporting:
    plugin: sitelog
