_core:
  default_config_hash: qxRdknZThnFBudeyxEFSc7ykDN2R19IbEYuIkGwkLa4
langcode: es
subject: 'One Time Password'
body: "Dear [user:name],\r\n    \r\nYour One Time Password for completing your Login Verification is: [user:email_tfa]\r\n    \r\nPlease use this Password to complete your transaction. Do not share this password with anyone.\r\n    \r\nThank you,\r\n[site:name] team"
routes: "email_tfa.verifiy\r\nuser.logout"
timeouts: 300
status: true
tracks: globally_enabled
user_one: true
ignore_role:
  - administrator
