_core:
  default_config_hash: NG_nmfm3Msyfhl9gKNbrk-Z9qb32c9bSgtaZ4ZbxbRg
langcode: es
encryption_profile: vss_encryption_profile
make_entities_uncacheable: true
default_properties:
  boolean: {  }
  color_field_type: {  }
  comment: {  }
  datetime: {  }
  email:
    - value
  link:
    - uri
    - title
  metatag: {  }
  timestamp: {  }
  video_embed_field: {  }
  list_float: {  }
  list_integer: {  }
  decimal: {  }
  float: {  }
  integer: {  }
  'field_ui:entity_reference:node': {  }
  entity_reference: {  }
  file: {  }
  image: {  }
  'field_ui:entity_reference:media': {  }
  opigno_scorm_package: {  }
  'field_ui:entity_reference:taxonomy_term': {  }
  'field_ui:entity_reference:user': {  }
  entity_reference_revisions: {  }
  'field_ui:entity_reference_revisions:paragraph': {  }
  list_string:
    - value
  text:
    - value
  text_long:
    - value
  text_with_summary:
    - value
    - summary
  string:
    - value
  string_long:
    - value
batch_size: 5
