_core:
  default_config_hash: E99p-j2YC4tVqQ7Gz4-I4cALOq2a8XHkvlQnxoV5EWY
session_limit_max: 1
session_limit_masquerade_ignore: false
session_limit_behaviour: 2
session_limit_logged_out_message_severity: warning
session_limit_admin_inclusion: 0
session_limit_roles:
  authenticated: 0
  administrator: -1
  country_admin: 0
  content_editor: 0
  super_admin: 0
