vss_common_config:
  vsscommonconfig__active_tab: edit-social-links
  phone: '8976576545'
  email: amrit@vss.com
  address: 'F block, Building Number 2A, ND - 110016'
  disclaimer_title: 'Welcome to the Virtual Safe Space!'
  disclaimer_description:
    value: "<p>This is a safe space designed for you to connect with peers and discover interesting content/answers to your questions.</p>\r\n\r\n<p><strong>Disclaimer:</strong></p>\r\n\r\n<p>Your browser history can be monitored without your knowledge, we recommend browsing in incognito mode in order to stay safe online. Here is how you can go to incognito mode:</p>\r\n"
    format: full_html
  disclaimer_image:
    - '11'
  header_country_code: ''
  header_phone: ''
  social_twitter: 0
  social_link_twitter: 'https://twitter.com'
  social_youtube: 0
  social_link_youtube: 'https://youtube.com'
  social_insta: 1
  social_link_insta: 'https://instgram.com'
  get_help: ''
  homepage_hero:
    testing: testing
    personal-safety: 0
    testing1: 0
    category: 0
    testing-3: 0
    testing-4: 0
    testing-5: 0
    testing-6: 0
    testing-7: 0
    hello-i-am-amrit: 0
    get-help-arab: 0
    get-help-kur: 0
    test: 0
    ads: 0
    test-test: 0
    test-test-spanish: 0
    hero-banner-arab: 0
    hero-banner: 0
    sasafdfss: 0
    fs-cate-ar: 0
    fs-cate: 0
    fs-cate-sp: 0
  submit: 'Save configuration'
  form_build_id: form-YofTsIpcj-U-7Z9tXGlXErPsKPU3c4NFVrWty42e3pU
  form_token: Wyrv6hGGOVLIHE7_IiKFHQ-VMNrdnEwQ8fUHyV5sIl8
  form_id: vss_common_config_form
  op: 'Save configuration'
