vss_common_config:
  vsscommonconfig__active_tab: edit-categories
  phone: '8976576546'
  email: amrit@vss.com
  address: 'F block, Building Number 2A, ND - 110016'
  disclaimer_title: 'Welcome to the Virtual Safe Space!'
  disclaimer_description:
    value: "<p>This is a safe space designed for you to connect with peers and discover interesting content/answers to your questions.</p>\r\n\r\n<p><strong>Disclaimer:</strong></p>\r\n\r\n<p>Your browser history can be monitored without your knowledge, we recommend browsing in incognito mode in order to stay safe online. Here is how you can go to incognito mode:</p>\r\n"
    format: full_html
  disclaimer_image:
    - '3671'
  header_country_code: ''
  header_phone: ''
  social_twitter: 1
  social_link_twitter: 'https://twitter.com'
  social_youtube: 1
  social_link_youtube: 'https://youtube.com'
  social_insta: 1
  social_link_insta: 'https://instgram.com'
  get_help: '46'
  homepage_hero:
    46: '46'
    286: '286'
    316: '316'
    341: '341'
    441: '441'
    381: 0
    411: 0
    551: 0
    556: 0
  location_selection_title: 'Seleccione su ubicación e idioma'
  location_selection_description:
    value: "<p>lorem ipsum doler siéntate amet</p>\r\n"
    format: full_html
  submit: 'Save configuration'
  form_build_id: form-nlpwE52jvjg0fgfPrqULCSP1WUeZcwESTKkD4fZ2KpA
  form_token: mrNGQCOK8X0R9WlYB1VmxNvvX08oWCTXybHG_tzvSxM
  form_id: vss_common_config_form
  op: 'Save configuration'
langcode: es
