settings:
  default_reset_button_label: 'إعادة الضبط'
  default_wizard_next_button_label: 'Next >'
  default_preview_next_button_label: معاينة
  default_preview_label: معاينة
element:
  default_more_title: المزيد
