label: 'Edit tip'
tips:
  tour-page:
    label: 'Tour edit'
    body: '<p>On this page you edit a tour.</p><p>Note that after saving a tour you need to make sure the tour file is copied for later use into a module config directory or into an issue queue.</p>'
  tour-label:
    label: Label
    body: '<p>The label is for administrative purposed. Used by Tour UI to list a Tour.</p>'
  tour-paths:
    label: Paths
    body: '<p>Here you define the path or paths a Tour should be displayed.</p><p>You may use * as a wildcard for a path element. Ie node/*edit</p>'
  tour-tips:
    label: Tips
    body: '<p>These are the tips.</p>'
