label: 'Edit tour'
tips:
  tour-page:
    label: 'Tour edit'
    body: '<p>On this page you edit a tour.</p><p>Note that after saving a tour you need to make sure the tour file is copied for later use into a module config directory or into an issue queue.</p>'
  tour-label:
    label: Label
    body: '<p>The label is for administrative purposed. Used by Tour UI to list a Tour.</p>'
  module:
    label: Module
    body: 'This is for declare a module dependency. The configuration system removes this tour when its module is uninstalled.'
  tour-routes:
    label: Routes
    body: '<p>Here you define the route or routes a Tour should be displayed.</p><p>You may use <a href="https://www.drupal.org/project/devel">Devel module</a> to find the route.</p>'
  tour-tips:
    label: Tips
    body: '<p>These are the tips.</p>'
