label: 'Affiliated content'
description: 'Find and manage content.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
      fields:
        node_bulk_form:
          action_title: 'With selection'
        title:
          label: Title
        type:
          label: 'Content Type'
          separator: ', '
        field_domain_access:
          label: Domain(s)
          separator: ', '
        field_domain_all_affiliates:
          label: 'All affiliates'
          separator: ', '
        name:
          label: Author
        status:
          label: Status
          settings:
            format_custom_true: Published
            format_custom_false: Unpublished
        changed:
          label: Updated
        operations:
          label: Operations
      filters:
        status:
          expose:
            label: Status
          group_info:
            label: 'Published status'
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        type:
          expose:
            label: Type
        title:
          expose:
            label: Title
        langcode:
          expose:
            label: Language
      title: 'Content assigned to All affiliates'
      empty:
        area_text_custom:
          content: 'No content available.'
      arguments:
        field_domain_access_target_id:
          exception:
            title: All
          title: '{{ arguments.field_domain_access_target_id }} content'
    display_title: Master
  page_1:
    display_options:
      menu:
        title: Content
      tab_options:
        title: Content
        description: 'Find and manage content'
      display_description: 'Default page for content per domain'
      filters:
        status:
          expose:
            label: Status
          group_info:
            label: 'Published status'
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        type:
          expose:
            label: Type
        title:
          expose:
            label: Title
        langcode:
          expose:
            label: Language
      title: Content
    display_title: 'Domain content page'
  page_2:
    display_title: 'All affiliates page'
    display_options:
      display_description: 'Lists content assigned to all affiliates'
      filters:
        status:
          expose:
            label: Status
          group_info:
            label: 'Published status'
            group_items:
              1:
                title: Published
              2:
                title: Unpublished
        type:
          expose:
            label: Type
        title:
          expose:
            label: Title
        langcode:
          expose:
            label: Language
        field_domain_access_target_id:
          expose:
            label: Domain
