label: 'Top viewed nodes'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      fields:
        title:
          separator: ', '
        nid:
          label: 'Count views'
          format_plural_string: !!binary MQNAY291bnQ=
      title: 'Top viewed nodes'
  block:
    display_title: Block
    display_options:
      block_description: 'Top viewed nodes'
