label: 'Node views count statistics'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        title:
          label: Title
          separator: ', '
        nid:
          label: 'Count views'
      empty:
        area:
          content:
            value: 'Users haven''t viewed anything yet.'
      title: 'Node views count statistics'
  page:
    display_title: Page
    display_options:
      menu:
        title: 'Node view count statistics'
