tips:
  exit-website:
    label: 'موقع الخروج'
    body: 'مهلا! أنا هنا لمساعدتك في تعلم كيفية "الخروج من موقع الويب" بسرعة'
  language-switcher:
    label: 'محوّل اللغة'
    body: 'مهلا! أنا هنا لمساعدتك في تعلم كيفية تغيير لغتك'
  chat:
    body: 'مهلا! تواصل معي أو اطرح أي سؤال في أي وقت الآن'
