label: اللغة
tips:
  language-overview:
    label: اللغات
  language-add:
    body: '<p> لإضافة المزيد من اللغات إلى موقعك، اضغط على زر "إضافة لغة". </p><p> ستظهر اللغات المضافة في قائمة اللغات ويمكن تحريرها أو حذفها.</p>'
  language-reorder:
    label: 'تسجيل اللغات'
