tips:
  search-api-index-fields-label:
    label: Label
  search-api-index-fields-machine-name:
    label: 'الاسم الآلي'
  search-api-index-fields-type:
    label: النوع
  search-api-index-fields-edit:
    label: 'تحرير الحقل'
  search-api-index-fields-submit:
    label: 'حفظ التغييرات'
