display:
  default:
    display_title: الرئيسي
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      fields:
        label:
          label: Label
          separator: ', '
        type:
          label: النوع
          separator: ', '
        paragraphs__target_id:
          separator: ', '
        langcode:
          label: اللغة
          separator: ', '
        id:
          label: 'المعرف ID'
          separator: ', '
        changed:
          separator: ', '
        operations:
          label: عمليات
      filters:
        label:
          expose:
            label: Label
          group_info:
            label: Label
        type:
          expose:
            label: النوع
  page_1:
    display_title: الصفحة
