label: 'Need Help View Ar'
display:
  default:
    display_options:
      title: 'تحتاج مساعدة'
      fields:
        nothing:
          label: تبوك
        field_email_id:
          label: 'عنوان الايميل'
        field_telephone_number:
          label: 'رقم هاتف'
        nothing_1:
          label: 'وسائل التواصل الاجتماعي'
        field_service_provider_name:
          label: 'اسم المنظمة'
        field_description:
          label: وصف
      header:
        area_text_custom:
          content: '</b>أنت تختار مدينة من الدولة<b>'
      pager:
        options:
          tags:
            next: '‹ التالي'
            previous: ' سابق ›'
            first: 'أولا »'
            last: '« الاخير '
