display:
  default:
    display_title: الرئيسي
    display_options:
      exposed_form:
        options:
          submit_button: Search
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
      fields:
        title:
          separator: ', '
        body:
          separator: ', '
        type:
          label: النوع
          separator: ', '
      filters:
        search_api_fulltext:
          expose:
            label: Search
      title: Search
  page:
    display_options:
      menu:
        title: Search
