label: بحث
display:
  default:
    display_options:
      title: بحث
      use_more_text: 'تحميل المزيد'
      header:
        result:
          content: 'جميع النتائج (@total)'
      exposed_form:
        options: {  }
      pager:
        options:
          views_infinite_scroll:
            button_text: 'تحميل المزيد'
