display:
  default:
    display_title: الرئيسي
    display_options:
      exposed_form:
        options:
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      fields:
        label:
          label: Label
        type:
          label: النوع
        langcode:
          label: اللغة
        id:
          label: 'المعرف ID'
        operations:
          label: عمليات
      filters:
        label:
          expose:
            label: Label
          group_info:
            label: Label
        type:
          expose:
            label: النوع
  page_1:
    display_title: الصفحة
