display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      fields:
        comment_bulk_form:
          action_title: إجراء
        subject:
          label: الموضوع
          separator: ', '
        uid:
          separator: ', '
        name:
          label: المؤلف
          separator: ', '
        entity_id:
          separator: ', '
        changed:
          separator: ', '
        operations:
          label: عمليات
        name_1:
          separator: ', '
      filters:
        subject:
          expose:
            label: الموضوع
        langcode:
          expose:
            label: اللغة
  page_unapproved:
    display_options:
      filters:
        subject:
          expose:
            label: الموضوع
        langcode:
          expose:
            label: اللغة
      fields:
        comment_bulk_form:
          action_title: إجراء
        subject:
          label: الموضوع
          separator: ', '
        uid:
          separator: ', '
        name:
          label: المؤلف
          separator: ', '
        entity_id:
          separator: ', '
        changed:
          separator: ', '
        operations:
          label: عمليات
        name_1:
          separator: ', '
