<?php

/**
 * @file
 * Contains erpw_in_app_notification.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function erpw_in_app_notification_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the erpw_in_app_notification module.
    case 'help.page.erpw_in_app_notification':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module will enable the inapp notification feature') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function erpw_in_app_notification_theme() {
  return [
    'erpw_in_app_notification' => [
      'render element' => 'children',
    ],
    'notification_block' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
    'user_notification' => [
      'variables' => [
        'user' => '',
        'role' => '',
        'service' => '',
        'common_var' => '',
      ],
    ],
    'notification_block' => [
      'variables' => [
        'count' => 0,
      ],
    ],
    'user_notification_modal' => [
      'variables' => [
        'combined' => '',
        'common_var' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_webform_submission_presave().
 */
function erpw_in_app_notification_webform_submission_presave($webform_submission) {
  $webform = $webform_submission->getWebform();

  // Notification implementation.
  if ($webform->get('category') == 'eRPW') {
    // Notify Focal Point if it is in in-rso create Notification entity for that.
    $erpw_workflow = $webform_submission->getElementData('erpw_workflow');
    if ($erpw_workflow['transition'] == 'submit_to_focal_point') {
      // Create notification master data.
      $notification_storage = \Drupal::entityTypeManager()->getStorage('notification_entity')->create([
        
      ]);
      $notification_storage->save();
    }
  }
  exit;
}