<?php

/**
 * @file
 * Functions to support theming in the erpw theme.
 */

/**
 * Implements hook_preprocess_HOOK()
 */
function erpw_preprocess_block(&$variables) {
  $userCurrent = \Drupal::currentUser();
  if ($userCurrent->isAuthenticated()) {

    $variables['user_name'] = $userCurrent->getAccountName();

  }

  $user_logged_in_name = $variables['user']->getDisplayName();

  $variables['user_logged_in_name'] = ucfirst($user_logged_in_name);
}
