display:
  default:
    display_title: ডিফল্ট
    display_options:
      fields:
        filename:
          label: নাম
        filesize:
          label: সাইজ
        status:
          label: স্ট্যাটাস
      exposed_form:
        options:
          submit_button: Filter
      filters:
        filename:
          expose:
            label: 'ফাইলের নাম'
        status:
          expose:
            label: স্ট্যাটাস
  page_2:
    display_options:
      arguments:
        fid:
          exception:
            title: সমস্ত
