<?php

/**
 * @file
 * Contains erpw_location.module.
 */

use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\Entity\User;

/**
 * Implements hook_help().
 */
function erpw_location_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the erpw_location module.
    case 'help.page.erpw_location':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function erpw_location_theme() {
  $theme = [];
  $theme['location'] = [
    'render element' => 'elements',
    'file' => 'location.page.inc',
    'template' => 'location',
  ];
  $theme['location_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'location.page.inc',
  ];
  $theme['manage_location_form'] = [
    'render element' => 'form',
    'template' => 'manage-location-form',
  ];
  $theme['homepage_user_location'] = [
    'variables' => [
      'title' => NULL,
      'description' => NULL,
      'location' => NULL,
      'tid' => NULL,
    ],
    'template' => 'homepage-user-location',
  ];
  $theme['pending_service_count'] = [
    'variables' => [
      'count' => NULL,
      'description' => NULL,
      'manage_service_link' => NULL,
    ],
    'template' => 'pending-service-count',
  ];

  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function erpw_location_theme_suggestions_location(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#location'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'location__' . $sanitized_view_mode;
  $suggestions[] = 'location__' . $entity->bundle();
  $suggestions[] = 'location__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'location__' . $entity->id();
  $suggestions[] = 'location__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_ENTITY_TYPE_predelete().
 */
function erpw_location_entity_predelete(EntityInterface $entity) {
  $type = $entity
    ->getEntityTypeId();
  if ($type == 'location') {
    $taxonomy_term_id = $entity->get('field_location_taxonomy_term')->getValue()[0]['target_id'];
    if ($term = Term::load($taxonomy_term_id)) {
      // Delete the term itself.
      $term->delete();
    }
  }
}

/**
 * Implements hook_taxonomy_term_delete().
 */
function erpw_location_taxonomy_term_delete($term) {
  $tid = $term->id();
  $delete_query = 'DELETE from erpw_location WHERE country_tid = ' . $tid .
    ' OR level1 =' . $tid .
    ' OR level2 =' . $tid .
    ' OR level3 =' . $tid .
    ' OR level4 =' . $tid;
  $query = \Drupal::database()->query($delete_query);
  $query->execute();
}

/**
 * Batch callback to dispatch the media entity batch operation to a service.
 */
function _import_location_batch_dispatcher() {
  $args = func_get_args();
  [$service, $method] = explode(':', array_shift($args));
  // The second argument (context) is passed by reference.
  $values = $args[1];
  $args[1] = &$values;
  call_user_func_array([\Drupal::service($service), $method], $args);
}

/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
function erpw_location_preprocess_page(&$variables) {
  // Check if the domain module is enabled.
  if (\Drupal::moduleHandler()->moduleExists('domain')) {
    $active_country_id = erpw_location_country_id_from_domain();
    $timezone = erpw_location_get_timezone_by_country_id($active_country_id);

    if ($timezone) {
      // Update the timezone for the current user.
      $user = User::load(\Drupal::currentUser()->id());
      if ($user) {
        $user->set('timezone', $timezone);
        $user->save();
      }
    }
  }
}

/**
 * Get the timezone for a given country ID.
 *
 * @param int $country_id
 *   The domain ID.
 *
 * @return string|null
 *   The timezone identifier (e.g., "Africa/Freetown", "Africa/Harare", "Europe/Istanbul"), or NULL if not found.
 */
function erpw_location_get_timezone_by_country_id($country_id) {
  switch ($country_id) {
    case 1:
      // Timezone for Zimbabwe.
      return 'Africa/Harare';

    case 6:
      // Timezone for Bangladesh.
      return 'Asia/Dhaka';

    case 11:
      // Timezone for Turkey cross-border.
      return 'Europe/Istanbul';

    case 16:
      // Timezone for Sierra Leone.
      return 'Africa/Freetown';

  }

  // Return NULL if the domain ID is not found.
  return NULL;
}

/**
 * Return country entity ID based on current subdomain.
 *
 * If not currently on a subdomain, return FALSE.
 */
function erpw_location_country_id_from_domain() {
  $active_domain = \Drupal::service('domain.negotiator')->getActiveDomain();
  if ($active_domain) {
    $domain_location_id = 'domain.location.' . $active_domain->id();
    $cf = \Drupal::service('config.factory');
    $tid = $cf->get($domain_location_id)->get('location');
    $location_entities = \Drupal::entityTypeManager()->getStorage('location')->loadByProperties([
      'field_location_taxonomy_term' => $tid,
    ]);
    return key($location_entities);
  }
  else {
    return FALSE;
  }
}

/**
 * Load country code from location taxonomy term.
 *
 * We do this in one shot because the machine names for domains *and* domain
 * locations are both wrong but if we get the domain directly we can ignore
 * that horror.  (That's only Zimbabwe but still.)
 */
function erpw_location_country_domain_from_tid($tid) {
  // This doesn't work but https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Config%21ConfigFactory.php/function/ConfigFactory%3A%3AlistAll/8.2.x should
  // $locations = \Drupal::config('domain.location');.
  // @todo Save in an alternate config rather than iterating through configs?
  // Also TODO we probably want to take any tid and find the root one.
  $cf = \Drupal::service('config.factory');
  $domain_locations = $cf->loadMultiple($cf->listAll('domain.location'));
  foreach ($domain_locations as $name => $domain_location) {
    if ($domain_location->get('location') == $tid) {
      // Name will be something like domain.location.bn_erefer_org
      // Need to load corresponding for example domain.record.bn_erefer_org.yml
      // Replace 'location' with 'record' in configuration name:
      $record_name = substr_replace($name, 'record', 7, 8);
      return $cf->get($record_name)->get('hostname');
    }
  }
}

/**
 * Utility function to recombine the parts of a parsed URL.
 *
 * Via https://www.php.net/manual/en/function.parse-url.php#106731
 */
function erpw_location_unparse_url($parsed_url) {
  $scheme   = isset($parsed_url['scheme']) ? $parsed_url['scheme'] . '://' : '';
  $host     = $parsed_url['host'] ?? '';
  $port     = isset($parsed_url['port']) ? ':' . $parsed_url['port'] : '';
  $user     = $parsed_url['user'] ?? '';
  $pass     = isset($parsed_url['pass']) ? ':' . $parsed_url['pass'] : '';
  $pass     = ($user || $pass) ? "$pass@" : '';
  $path     = $parsed_url['path'] ?? '';
  $query    = isset($parsed_url['query']) ? '?' . $parsed_url['query'] : '';
  $fragment = isset($parsed_url['fragment']) ? '#' . $parsed_url['fragment'] : '';
  return "$scheme$user$pass$host$port$path$query$fragment";
}
