<?php

/**
 * @file
 * Contains erpw_pathway.module.
 */

use Drupal\views\ViewExecutable;
use Drupal\user\Entity\User;
use Drupal\views\Plugin\views\query\QueryPluginBase;

/**
 * Implementing erpw_pathway_preprocess_views_view_field().
 */
function erpw_pathway_preprocess_views_view_field(&$variables) {
  $view = $variables['view'];
  if ($view->id() == 'referral_pathway_listing' || $view->id() == 'manage_service' || $view->id() == 'service_list') {
    if ($variables['field']->field == 'field_location') {
      $row = $variables['field']->getValue($variables['row']);
      $loc_name = [];
      if ($row[0]) {
        $parent_tid = \Drupal::service('erpw_location.location_services')->getAllAncestors($row[0]);
        $last_sibling_terms = [];
        $parents = [];
        if (count($row) > 1) {
          array_shift($row);
          $last_sibling_terms = $row;
        }
        if (!empty($last_sibling_terms)) {
          $parents = array_merge($parent_tid, $last_sibling_terms);
        }
        else {
          $parents = $parent_tid;
        }
        $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadMultiple(array_reverse($parents));
        foreach ($terms as $term) {
          $loc_name[] = $term->label();
        }
      }
      $variables['output'] = implode(', ', $loc_name);
    }
  }
}

/**
 * Implements hook_views_query_alter().
 */
function erpw_pathway_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == "referral_pathway_on_homepage" || $view->id() == "service_list") {
    $ptids = [];
    $current_user = \Drupal::currentUser();
    $user_entity = User::load($current_user->id());
    if ($user_entity->hasField('field_location_details') && !$user_entity->get('field_location_details')->isEmpty()) {
      $location_id = $user_entity->get('field_location_details')->getValue()[0]['value'];
      $ptids = \Drupal::service('erpw_location.location_services')->getChildrenByParent($location_id);
    }
    if (!empty($ptids)) {
      foreach ($query->where as &$condition_group) {
        foreach ($condition_group['conditions'] as &$condition) {
          if ($condition['field'] == 'node__field_location.field_location_target_id') {
            $condition = [
              'field' => 'node__field_location.field_location_target_id',
              'value' => $ptids,
              'operator' => 'IN',
            ];
            break;
          }
        }
      }
    }
  }
}
