<?php

/**
 * @file
 * Contains vss_custom.module.
 */

use Drupal\menu_link_content\Entity\MenuLinkContent;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_HOOK().
 */
function vss_custom_preprocess_page(&$variables) {
}

/**
 * Implements hook_theme().
 */
function vss_custom_theme() {
  return [
    'exit_website' => [
      'variables' => [
        'data' => [],
      ],
    ],
    'disclaimer_pop_up_block' => [
      'variables' => [
        'content' => NULL,
      ],
      'render element' => 'children',
    ],
    'social_icons' => [
      'variables' => [
        'content' => NULL,
      ],
      'render element' => 'children',
    ],
    'video_embed_iframe' => [
      'variables' => [
        'url' => '',
        'query' => [],
        'attributes' => [],
        'fragment' => '',
        'language' => '',
        'video_id' => '',
      ],
    ],
  ];
}

/**
 * Use language label for the language switcher.
 */
function vss_custom_preprocess_links__language_block(&$variables) {

  if (isset($variables['links'])) {
    // Get the language list used and provided by Drupal core.
    $language_manager = \Drupal::languageManager();
    $language_list = $language_manager::getStandardLanguageList();

    // Go through each link present in the output and change it's title.
    foreach ($variables['links'] as $link_langcode => $link) {
      $variables['links'][$link_langcode]['link']['#title'] = $language_list[$link_langcode][1];
    }
  }
}

/**
 * Use taxonomy presave to create new menu.
 */
function vss_custom_taxonomy_term_presave($term) {
  if ($term->get('vid')->target_id == 'categories') {
    if ($term->isNew()) {
      $menu_name = strpos($term->get('field_domain')->target_id, "iq") ? 'iraq-navigation-header-menu' : 'navigation-header-menu';
      $links = \Drupal::entityTypeManager()->getStorage('menu_link_content')->loadByProperties(
      ['field_discover_dropdown' => 1, 'menu_name' => $menu_name]);
      if ($link = reset($links)) {
        $uuid = $link->get('uuid')->value;
      }
      $menu_link = MenuLinkContent::create([
        'title' => $term->get('name')->value,
        'link' => ['uri' => 'internal:#'],
        'menu_name' => strpos($term->get('field_domain')->target_id, "iq") ? 'iraq-navigation-header-menu' : 'navigation-header-menu',
        'langcode' => strpos($term->get('field_domain')->target_id, "iq") ? 'ar' : 'en',
        'weight' => $term->get('weight')->value,
        'expanded' => FALSE,
        'parent' => 'menu_link_content:' . $uuid,
      ]);
      $menu_link->save();

      if (strpos($term->get('field_domain')->target_id, "iq")) {
        $term->langcode->value = 'ar';
      }
    }
    else {
      $links = \Drupal::entityTypeManager()->getStorage('menu_link_content')->loadByProperties(['title' => $term->original->get('name')->value]);
      if ($link = reset($links)) {
        if (!$link->hasTranslation($term->get('langcode')->value)) {
          $link->addTranslation($term->get('langcode')->value, ['title' => $term->get('name')->value])->save();
        }
        else {
          $link->title->value = $term->get('name')->value;
          $link->langcode->value = $term->get('langcode')->value;
          $link->weight->value = $term->get('weight')->value;
          $link->save();
        }
      }
    }
  }
  if ($term->get('vid')->target_id == 'sub_category') {
    if (strpos($term->get('field_domain')->target_id, "iq")) {
      $term->langcode->value = 'ar';
    }
  }
}

/**
 * Use taxonomy presave to delete menu.
 */
function vss_custom_taxonomy_term_delete($term) {
  if ($term->get('vid')->target_id == 'categories') {
    $links = \Drupal::entityTypeManager()->getStorage('menu_link_content')->loadByProperties(['title' => $term->get('name')->value]);
    if ($link = reset($links)) {
      $link->delete();
    }
  }
}

/**
 * Alter the video_embed_field plugin definitions.
 *
 * This hook allows you alter the plugin definitions managed by ProviderManager.
 * This could be useful if you wish to remove a particular definition or perhaps
 * replace one with your own implementation (as demonstrated).
 */
function vss_custom_video_embed_field_provider_info_alter(&$definitions) {
  // Replace the YouTube provider class with another implementation.
  $definitions['youtube']['class'] = 'Drupal\vss_custom\Plugin\video_embed_field\Provider\CustomYouTubeProvider';
}

/**
 * Implements hook_form_alter().
 */
function vss_custom_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (\Drupal::request()->attributes->has('_route')) {
    if (\Drupal::request()->attributes->get('_route') == 'entity.node.content_translation_add') {
      \Drupal::messenger()->addWarning(t('You are modifying content for @language language', ['@language' => \Drupal::languageManager()->getCurrentLanguage()->getName()]));
    }
  }
}
