<?php

/**
 * @file
 * Contains vss_custom.module.
 */

use Drupal\menu_link_content\Entity\MenuLinkContent;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function vss_custom_theme() {
  return [
    'exit_website' => [
      'variables' => [
        'data' => [],
      ],
    ],
    'disclaimer_pop_up_block' => [
      'variables' => [
        'content' => NULL,
      ],
      'render element' => 'children',
    ],
    'social_icons' => [
      'variables' => [
        'content' => NULL,
      ],
      'render element' => 'children',
    ],
    'recommended_related_content_block' => [
      'variables' => [
        'content' => NULL,
      ],
      'render element' => 'children',
    ],
    'video_embed_iframe' => [
      'variables' => [
        'url' => '',
        'query' => [],
        'attributes' => [],
        'fragment' => '',
        'language' => '',
        'video_id' => '',
      ],
      'global_sticky_block' => [
        'variables' => [
          'content' => NULL,
          'lang_code' => '',
        ],
        'render element' => 'children',
      ],
    ],
  ];
}

/**
 * Use language label for the language switcher.
 */
function vss_custom_preprocess_links__language_block(&$variables) {

  if (isset($variables['links'])) {
    // Get the language list used and provided by Drupal core.
    $language_manager = \Drupal::languageManager();
    $language_list = $language_manager::getStandardLanguageList();

    // Go through each link present in the output and change it's title.
    foreach ($variables['links'] as $link_langcode => $link) {
      $variables['links'][$link_langcode]['link']['#title'] = $language_list[$link_langcode][1];
    }
  }
}

/**
 * Use taxonomy presave to create new menu.
 */
function vss_custom_taxonomy_term_presave($term) {
  if ($term->get('vid')->target_id == 'categories' && empty($term->get('field_sub_category')->value)) {
    if ($term->isNew()) {
      $menu_name = strpos($term->get('field_domain')->target_id, "iq") ? 'iraq-navigation-header-menu' : 'navigation-header-menu';
      $links = \Drupal::entityTypeManager()->getStorage('menu_link_content')->loadByProperties(
      ['field_discover_dropdown' => 1, 'menu_name' => $menu_name]);
      if ($link = reset($links)) {
        $uuid = $link->get('uuid')->value;
      }
      $menu_link = MenuLinkContent::create([
        'title' => $term->get('name')->value,
        'link' => ['uri' => 'internal:#'],
        'menu_name' => strpos($term->get('field_domain')->target_id, "iq") ? 'iraq-navigation-header-menu' : 'navigation-header-menu',
        'langcode' => strpos($term->get('field_domain')->target_id, "iq") ? 'ar' : 'en',
        'weight' => $term->get('weight')->value,
        'expanded' => FALSE,
        'field_icon' => [
          'target_id' => $term->get('field_icon')->target_id,
          'alt' => $term->get('field_icon')->alt,
        ],
        'parent' => 'menu_link_content:' . $uuid,
      ]);
      $menu_link->save();

      if (strpos($term->get('field_domain')->target_id, "iq")) {
        $term->langcode->value = 'ar';
      }
    }
    else {
      $links = \Drupal::entityTypeManager()->getStorage('menu_link_content')->loadByProperties(['title' => $term->original->get('name')->value]);
      if ($link = reset($links)) {
        if (!$link->hasTranslation($term->get('langcode')->value)) {
          $link->addTranslation($term->get('langcode')->value, ['title' => $term->get('name')->value])->save();
        }
        else {
          $link->title->value = $term->get('name')->value;
          $link->langcode->value = $term->get('langcode')->value;
          $link->weight->value = $term->get('weight')->value;
          $link->field_icon->target_id = $term->get('field_icon')->target_id;
          $link->field_icon->alt = $term->get('field_icon')->alt;
          $link->save();
        }
      }
      $term->get('parent')->target_id = 0;
    }
  }
  if ($term->get('vid')->target_id == 'categories' && $term->get('field_sub_category')->value == 1) {
    if (strpos($term->get('field_domain')->target_id, "iq")) {
      $term->langcode->value = 'ar';
    }
    $term->get('parent')->target_id = $term->get('field_category_reference')->target_id;
  }
}

/**
 * Use taxonomy presave to delete menu.
 */
function vss_custom_taxonomy_term_delete($term) {
  if ($term->get('vid')->target_id == 'categories') {
    $links = \Drupal::entityTypeManager()->getStorage('menu_link_content')->loadByProperties(['title' => $term->get('name')->value]);
    if ($link = reset($links)) {
      $link->delete();
    }
  }
}

/**
 * Use form alter.
 */
function vss_custom_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if ($form_id == 'taxonomy_term_categories_form') {
    $form['description']['widget'][0]['#required'] = 'true';
    $form['field_category_reference']['widget']['#options'] = ['_none' => 'Select a value'] + get_all_parent_categories();
    $form['#validate'][] = 'validate_category';
  }
  $language_manager = \Drupal::languageManager()->getCurrentLanguage();
  // Adding warning message.
  $request = \Drupal::request();
  if ($request->attributes->has('_route')) {
    if ($request->attributes->get('_route') == 'entity.node.content_translation_add') {
      \Drupal::messenger()->addWarning(t('You are modifying content for @language language', ['@language' => $language_manager->getName()]));
    }
    if ($request->attributes->get('_route') == 'entity.media.content_translation_add') {
      \Drupal::messenger()->addWarning(t('You are modifying media for @language language', ['@language' => $language_manager->getName()]));
    }
    if ($request->attributes->get('_route') == 'entity.media.collection') {
      $messenger = \Drupal::messenger();
      $messenger->deleteByType('warning');
    }
  }
  if ($form_id == 'menu_link_content_menu_link_content_form') {
    unset($form['weight']);
  }
  if ($form_id == 'taxonomy_term_sub_category_form') {
    $form['relations']['#weight'] = 7;
  }
}

/**
 * Validate category.
 */
function validate_category(&$form, &$form_state) {
  $subcat = $form_state->getValue('field_sub_category')['value'];
  $subcat_thumbail = $form_state->getValue('field_sub_category_thumbnail')[0]['alt'];
  $cat_ref = $form_state->getValue('field_category_reference');
  $cat_color = $form_state->getValue('field_category_color')[0]['color'];
  $icon = $form_state->getValue('field_icon')[0]['alt'];

  if ($subcat) {
    if (empty($subcat_thumbail)) {
      $form_state->setErrorByName('field_sub_category_thumbnail', t('Sub Category Thumbnail is required'));
    }
    if (empty($cat_ref)) {
      $form_state->setErrorByName('field_category_reference [0][target_id', t('Category reference field is required'));
    }
  }
  else {
    if (empty($cat_color)) {
      $form_state->setErrorByName('field_category_color', t('Category color field is required'));
    }
    if (empty($icon)) {
      $form_state->setErrorByName('field_icon', t('Icon field is required'));
    }
  }
}

/**
 * Alter the video_embed_field plugin definitions.
 *
 * This hook allows you alter the plugin definitions managed by ProviderManager.
 * This could be useful if you wish to remove a particular definition or perhaps
 * replace one with your own implementation (as demonstrated).
 */
function vss_custom_video_embed_field_provider_info_alter(&$definitions) {
  // Replace the YouTube provider class with another implementation.
  $definitions['youtube']['class'] = 'Drupal\vss_custom\Plugin\video_embed_field\Provider\CustomYouTubeProvider';
}

/**
 * Get all categories.
 */
function get_all_parent_categories() {
  $query = \Drupal::database()->select('taxonomy_term_field_data', 't');
  $query->join('taxonomy_term__field_domain', 'fd', 'fd.entity_id = t.tid');
  $query->leftjoin('taxonomy_term__field_sub_category', 'sc', 'sc.entity_id = t.tid');
  $query->condition('fd.bundle', 'categories');
  $query->condition('sc.field_sub_category_value', 1, '!=');
  $query->fields('t', ['tid']);
  $query->fields('t', ['name']);
  $terms = $query->execute()->fetchAllKeyed(0, 1);
  return $terms;
}

/**
 * Implements hook_preprocess_block().
 */
function vss_custom_preprocess_block(&$variables) {
  if ($variables['elements']['#base_plugin_id'] == 'block_content') {
    if ($variables['label'] !== '') {
      $variables['label'] = $variables['content']['#block_content']->label();
    }
  }
}

/**
 * Implements hook_pquery_sort_by_random_alter().
 */
function vss_custom_query_sort_by_random_alter($query) {
  $query->orderRandom();
}
