display:
  default:
    display_title: 'طے شدہ'
    display_options:
      pager:
        options:
          tags:
            next: ‹‹
            previous: ››
      exposed_form:
        options:
          exposed_sorts_label: 'کی طرف سے  کی گئی مرتب سازی'
