display:
  default:
    display_title: 'طے شدہ'
    display_options:
      exposed_form:
        options:
          exposed_sorts_label: 'کی طرف سے  کی گئی مرتب سازی'
      use_more_text: مزید
  block_1:
    display_title: بلاک
