display:
  default:
    display_title: 'طے شدہ'
    display_options:
      fields:
        info:
          label: 'بلاک کی وضاحت'
        operations:
          label: معاملات
      pager:
        options:
          tags:
            previous: '› گزشتہ'
      exposed_form:
        options:
          exposed_sorts_label: 'کی طرف سے  کی گئی مرتب سازی'
      filters:
        info:
          expose:
            label: 'بلاک کی وضاحت'
