label: متن
display:
  default:
    display_title: 'طے شدہ'
    display_options:
      title: متن
      fields:
        title:
          label: عنوان
        name:
          label: مصنف
        status:
          label: حالت
        operations:
          label: معاملات
      pager:
        options:
          tags:
            previous: '› گزشتہ'
            first: '» ابتدائی'
      exposed_form:
        options:
          submit_button: فلٹر
          exposed_sorts_label: 'کی طرف سے  کی گئی مرتب سازی'
      filters:
        title:
          expose:
            label: عنوان
        status:
          expose:
            label: حالت
        langcode:
          expose:
            label: زبان
  page_1:
    display_options:
      menu:
        title: متن
      tab_options:
        title: متن
