display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: فلٹر
          exposed_sorts_label: 'کی طرف سے  کی گئی مرتب سازی'
      pager:
        options:
          tags:
            previous: '› گزشتہ'
            first: '» ابتدائی'
      fields:
        title:
          label: عنوان
        name:
          label: مصنف
        status:
          label: حالت
        operations:
          label: معاملات
      filters:
        status:
          expose:
            label: حالت
        type:
          expose:
            label: قِسم
        title:
          expose:
            label: عنوان
        langcode:
          expose:
            label: زبان
  page_1:
    display_options:
      menu:
        title: متن
      tab_options:
        title: متن
      filters:
        status:
          expose:
            label: حالت
        type:
          expose:
            label: قِسم
        title:
          expose:
            label: عنوان
        langcode:
          expose:
            label: زبان
      title: متن
  page_2:
    display_options:
      filters:
        status:
          expose:
            label: حالت
        type:
          expose:
            label: قِسم
        title:
          expose:
            label: عنوان
        langcode:
          expose:
            label: زبان
