display:
  default:
    display_title: 'طے شدہ'
    display_options:
      fields:
        type:
          label: قِسم
        link:
          label: معاملات
      pager:
        options:
          tags:
            next: ‹‹
            previous: ››
      exposed_form:
        options:
          submit_button: فلٹر
          exposed_sorts_label: 'کی طرف سے  کی گئی مرتب سازی'
      filters:
        type:
          expose:
            label: قِسم
