display:
  default:
    display_title: 'طے شدہ'
    display_options:
      fields:
        name:
          label: 'اسم صارف'
        status:
          label: حالت
        operations:
          label: معاملات
      pager:
        options:
          tags:
            previous: '› گزشتہ'
            first: '» ابتدائی'
      exposed_form:
        options:
          submit_button: فلٹر
          exposed_sorts_label: 'کی طرف سے  کی گئی مرتب سازی'
      filters:
        status:
          group_info:
            label: حالت
      use_more_text: مزید
  page_1:
    display_options:
      menu:
        title: فہرست
