display:
  default:
    display_title: 'طے شدہ'
    display_options:
      pager:
        options:
          tags:
            previous: '› گزشتہ'
            first: '» ابتدائی'
      exposed_form:
        options:
          exposed_sorts_label: 'کی طرف سے  کی گئی مرتب سازی'
