_core:
  default_config_hash: qxRdknZThnFBudeyxEFSc7ykDN2R19IbEYuIkGwkLa4
langcode: en
subject: 'One Time Password'
body: "Dear [user:name],\r\n    \r\nYour One Time Password for completing your transaction eRPW TFA Verification is: [user:email_tfa]\r\n    \r\nPlease use this Password to complete your transaction. Do not share this password with anyone.\r\n    \r\nThank you,\r\n[site:name] team"
routes: "email_tfa.verifiy\r\nuser.logout"
timeouts: 300
status: false
tracks: globally_enabled
user_one: false
role_exclusion_type: disable_for
ignore_role:
  - administrator
  - super_admin
security_code_label_text: 'One-time security code'
security_code_description_text: 'We sent you an email containing your one-time security code. Please enter the code provided to proceed.'
security_code_verify_text: Verify
verification_succeeded_message: 'One-time security code verification succeeded.'
verification_failed_message: 'One-time security code verification failed.'
security_code_length: 4
security_code_interrupt_text: Cancel
verification_interrupted_message: 'One-time security code verification interrupted.'
