_core:
  default_config_hash: g4qz7cPnloXFwtnLYfIKI2VS0gf_UFOz_I2uQiiulC8
apikey: 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
test_defaults:
  to: nishtha.pradhan@qed42.com
  subject: 'Test Email from SendGrid Module'
  body:
    value: 'Test Message for SendGrid.'
    format: plain_text
  from_name: eRPW
  to_name: QED42
  reply_to: no-reply@erefer.org
trackopens: 0
trackclicks: 0
