<?php

/**
 * @file
 * Contains unicef_security.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function unicef_security_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  // Turn off autocomplete on user the forms.
  if ($form_id == 'user_login_form') {
    $form['name']['#attributes']['autocomplete'] = 'off';
    $form['pass']['#attributes']['autocomplete'] = 'off';
  }
}
