configArray:
  article:
    article:
      uuid: uuid
  organisation:
    organisation: {  }
  page:
    page: {  }
  referral_path_way:
    referral_path_way: {  }
  service_provider:
    service_provider: {  }
  service_type:
    service_type: {  }
nodeTypeConfig:
  article:
    exclude_all: 1
    Article:
      nid: nid
      uuid: uuid
      vid: vid
      langcode: langcode
      type: type
      revision_timestamp: revision_timestamp
      revision_uid: revision_uid
      revision_log: revision_log
      status: status
      uid: uid
      title: title
      created: created
      changed: changed
      promote: promote
      sticky: sticky
      default_langcode: default_langcode
      revision_default: revision_default
      revision_translation_affected: revision_translation_affected
      moderation_state: moderation_state
      metatag: metatag
      path: path
      menu_link: menu_link
      content_translation_source: content_translation_source
      content_translation_outdated: content_translation_outdated
      body: body
      comment: comment
      field_domain_access: field_domain_access
      field_domain_all_affiliates: field_domain_all_affiliates
      field_domain_source: field_domain_source
      field_image: field_image
      field_tags: field_tags
  organisation:
    exclude_all: 1
    Organisation:
      nid: nid
      uuid: uuid
      vid: vid
      langcode: langcode
      type: type
      revision_timestamp: revision_timestamp
      revision_uid: revision_uid
      revision_log: revision_log
      status: status
      uid: uid
      title: title
      created: created
      changed: changed
      promote: promote
      sticky: sticky
      default_langcode: default_langcode
      revision_default: revision_default
      revision_translation_affected: revision_translation_affected
      moderation_state: moderation_state
      metatag: metatag
      path: path
      menu_link: menu_link
      content_translation_source: content_translation_source
      content_translation_outdated: content_translation_outdated
      body: body
      comment: comment
      field_domain_access: field_domain_access
      field_domain_all_affiliates: field_domain_all_affiliates
      field_domain_source: field_domain_source
      field_image: field_image
      field_tags: field_tags
  page:
    exclude_all: 1
    'Basic page':
      nid: nid
      uuid: uuid
      vid: vid
      langcode: langcode
      type: type
      revision_timestamp: revision_timestamp
      revision_uid: revision_uid
      revision_log: revision_log
      status: status
      uid: uid
      title: title
      created: created
      changed: changed
      promote: promote
      sticky: sticky
      default_langcode: default_langcode
      revision_default: revision_default
      revision_translation_affected: revision_translation_affected
      moderation_state: moderation_state
      metatag: metatag
      path: path
      menu_link: menu_link
      content_translation_source: content_translation_source
      content_translation_outdated: content_translation_outdated
      body: body
      comment: comment
      field_domain_access: field_domain_access
      field_domain_all_affiliates: field_domain_all_affiliates
      field_domain_source: field_domain_source
      field_image: field_image
      field_tags: field_tags
  referral_path_way:
    exclude_all: 1
    'Referral Pathway':
      nid: nid
      uuid: uuid
      vid: vid
      langcode: langcode
      type: type
      revision_timestamp: revision_timestamp
      revision_uid: revision_uid
      revision_log: revision_log
      status: status
      uid: uid
      title: title
      created: created
      changed: changed
      promote: promote
      sticky: sticky
      default_langcode: default_langcode
      revision_default: revision_default
      revision_translation_affected: revision_translation_affected
      moderation_state: moderation_state
      metatag: metatag
      path: path
      menu_link: menu_link
      content_translation_source: content_translation_source
      content_translation_outdated: content_translation_outdated
      body: body
      comment: comment
      field_domain_access: field_domain_access
      field_domain_all_affiliates: field_domain_all_affiliates
      field_domain_source: field_domain_source
      field_image: field_image
      field_tags: field_tags
      field_location: field_location
      field_section: field_section
  service_provider:
    exclude_all: 0
    Service:
      nid: nid
      uuid: uuid
      vid: vid
      type: type
      revision_timestamp: revision_timestamp
      revision_uid: revision_uid
      revision_log: revision_log
      uid: uid
      changed: changed
      revision_default: revision_default
      revision_translation_affected: revision_translation_affected
      content_translation_source: content_translation_source
      content_translation_outdated: content_translation_outdated
      langcode: 0
      status: 0
      title: 0
      created: 0
      promote: 0
      sticky: 0
      default_langcode: 0
      moderation_state: 0
      metatag: 0
      path: 0
      menu_link: 0
      body: 0
      comment: 0
      field_domain_access: 0
      field_domain_all_affiliates: 0
      field_domain_source: 0
      field_image: 0
      field_tags: 0
      field_location: 0
      field_section: 0
      field_accessibility_for_persons_: 0
      field_add_more_details_service: 0
      field_age_group: 0
      field_cost_of_service: 0
      field_email_backup_focal_point: 0
      field_email_of_focal_point: 0
      field_mode: 0
      field_name_backup_focalpoint_ref: 0
      field_name_of_the_focal_point: 0
      field_number_of_staff_providing_: 0
      field_opening_hours: 0
      field_p_code: 0
      field_phone_number: 0
      field_phone_number_backup_focalp: 0
      field_phone_number_of_focal_poin: 0
      field_select_organisation: 0
      field_service_type: 0
      field_target_group: 0
      field_transportation_available: 0
  service_type:
    exclude_all: 1
    'Service type':
      nid: nid
      uuid: uuid
      vid: vid
      langcode: langcode
      type: type
      revision_timestamp: revision_timestamp
      revision_uid: revision_uid
      revision_log: revision_log
      status: status
      uid: uid
      title: title
      created: created
      changed: changed
      promote: promote
      sticky: sticky
      default_langcode: default_langcode
      revision_default: revision_default
      revision_translation_affected: revision_translation_affected
      moderation_state: moderation_state
      metatag: metatag
      path: path
      menu_link: menu_link
      content_translation_source: content_translation_source
      content_translation_outdated: content_translation_outdated
      body: body
      comment: comment
      field_domain_access: field_domain_access
      field_domain_all_affiliates: field_domain_all_affiliates
      field_domain_source: field_domain_source
      field_image: field_image
      field_tags: field_tags
      field_location: field_location
      field_section: field_section
      field_accessibility_for_persons_: field_accessibility_for_persons_
      field_add_more_details_service: field_add_more_details_service
      field_age_group: field_age_group
      field_cost_of_service: field_cost_of_service
      field_email_backup_focal_point: field_email_backup_focal_point
      field_email_of_focal_point: field_email_of_focal_point
      field_mode: field_mode
      field_name_backup_focalpoint_ref: field_name_backup_focalpoint_ref
      field_name_of_the_focal_point: field_name_of_the_focal_point
      field_number_of_staff_providing_: field_number_of_staff_providing_
      field_opening_hours: field_opening_hours
      field_p_code: field_p_code
      field_phone_number: field_phone_number
      field_phone_number_backup_focalp: field_phone_number_backup_focalp
      field_phone_number_of_focal_poin: field_phone_number_of_focal_poin
      field_select_organisation: field_select_organisation
      field_service_type: field_service_type
      field_target_group: field_target_group
      field_transportation_available: field_transportation_available
      field_service_type_color: field_service_type_color
      field_service_type_icon: field_service_type_icon
  fields__active_tab: edit-fields-service-provider
