_core:
  default_config_hash: x6bhN6WZwfVUI_LLMvRJIUW_2c26VTaBozbfXmJWmro
seckit_xss:
  csp:
    checkbox: true
    vendor-prefix:
      x: false
      webkit: false
    report-only: false
    default-src: '''self'' *.erefer.org:* ''unsafe-inline'' ''unsafe-eval'' *.sharethis.com:* *.cloudflare.com:* *.google-analytics.com:* *.googletagmanager.com:* *.gstatic.com:* *.googleapis.com:* *.fontawesome.com:* *.addtoany.com:* *.disqus.com:* *.facebook.com:* *.facebook.net:* *.google.com:* *.linkedin.com:* *.twitter.com:* *.youtube.com:* *.vimeo.com:* *.instagram.com *.newrelic.com:* *.nr-data.net:* *.jquery.js:* *.chosen.css:* *.opencagedata.com:* *.jsdelivr.net:* *.unpkg.com:* https://unpkg.com/@fonticonpicker/fonticonpicker@3.1.1/dist/js/jquery.fonticonpicker.min.js https://unpkg.com/@fonticonpicker/fonticonpicker@3.1.1/dist/css/base/jquery.fonticonpicker.min.css https://unpkg.com/@fonticonpicker/fonticonpicker@3.1.1/dist/css/themes/grey-theme/jquery.fonticonpicker.grey.min.css https://unpkg.com/@fonticonpicker/fonticonpicker@3.1.1/dist/fonts/iconpicker.woff?90190138 data:'
    script-src: '''self'' ''unsafe-inline'' ''unsafe-eval'' *.erefer.org:* *.google-analytics.com:* *.googletagmanager.com:* *.jsdelivr.net:* https://unpkg.com/@fonticonpicker/fonticonpicker@3.1.1/dist/js/jquery.fonticonpicker.min.js'
    object-src: ''
    style-src: '''self'' ''unsafe-inline'' *.jsdelivr.net:* *.googleapis.com:* *.cloudflare.com:* https://unpkg.com/@fonticonpicker/fonticonpicker@3.1.1/dist/css/base/jquery.fonticonpicker.min.css https://unpkg.com/@fonticonpicker/fonticonpicker@3.1.1/dist/css/themes/grey-theme/jquery.fonticonpicker.grey.min.css'
    img-src: '''self'' data:'
    media-src: ''
    frame-src: ''
    frame-ancestors: '''self'''
    child-src: ''
    font-src: '''self'' ''unsafe-inline'' ''unsafe-eval'' *.gstatic.com:* *.googleusercontent.com:* *.googleapis.com:* *.googleapis.com:* *.fontawesome.com:* *.jsdelivr.net:* *.cloudflare.com:* data: https://unpkg.com/@fonticonpicker/fonticonpicker@3.1.1/dist/fonts/iconpicker.woff?90190138'
    connect-src: ''
    report-uri: report-csp-violation
    upgrade-req: false
    policy-uri: ''
  x_xss:
    seckit_x_xss_option_disable: Disabled
    seckit_x_xss_option_0: '0'
    seckit_x_xss_option_1: 1;
    seckit_x_xss_option_1_block: '1; mode=block'
    select: 0
seckit_csrf:
  origin: false
  origin_whitelist: ''
seckit_clickjacking:
  js_css_noscript: false
  noscript_message: 'Sorry, you need to enable JavaScript to visit this website.'
  x_frame: '1'
  x_frame_allow_from: ''
seckit_ssl:
  hsts: true
  hsts_subdomains: false
  hsts_max_age: 31536000
  hsts_preload: false
seckit_ct:
  expect_ct: false
  max_age: 86400
  report_uri: ''
  enforce: false
seckit_fp:
  feature_policy: false
  feature_policy_policy: ''
seckit_various:
  from_origin: false
  from_origin_destination: same
  referrer_policy: false
  referrer_policy_policy: no-referrer
  disable_autocomplete: false
