#!/usr/bin/env bash

## Run phpcbf command to run php code beautifier against custom code.
##
## Usage: fin phpcbf

fin run phpcbf \
    --standard="Drupal,DrupalPractice" -n \
    --extensions="php,module,inc,install,test,profile,theme" \
    --ignore="*.features.*,*.pages*.inc" \
    docroot/modules/custom docroot/themes/custom docroot/profiles/custom
