tips:
  language-switcher:
    body: 'شوێن و زمانی خوازراوت هەڵبژێرە لە خوارەوە بۆ دەستڕاگەیشتنت بەو زانیاری و خزمەتگوزارییانەی زۆرترین پەیوەندییان هەیە بەو شوێنەی تێیدایت.'
  chat:
    body: 'ئەگەر تۆ یان كەسێك كە دەیناسیت و پێویستی بە هاوكارییە و بەدوای خزمەتگوزارییەكی دیاریكراودا دەگەڕێیت، بە تایبەتی ئەگەری دووچاری توندوتیژی بوویتە، ئەوا كلیك لەسەر ئەم بەستەرە-لینك- بكە بۆ بەدەستهێنانی زانیاری لەبارەی خزمەتگوزارییە فەراهەمكراوەكان لە ناوچەكەدا و ئایا كەی و چۆن دەتوانیت بەدەستیان بهێنیت'
  exit-website:
    body: '.كلیك لێرە بكە دەرچوون لە وێبسایت'
