label: 'کێ نوێیە'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      title: 'کێ نوێیە'
  block_1:
    display_title: 'کێ نوێیە'
    display_options:
      block_description: 'کێ نوێیە'
      block_category: بەکارهێنەر
