label: 'Moderated content'
display:
  default:
    display_title: Master
    display_options:
      title: 'Moderated content'
      fields:
        title:
          label: ناونیشان
        type:
          label: 'جۆری ناوەڕۆک'
        name:
          label: نووسەر
        changed:
          label: Updated
        operations:
          label: کاره‌کان
      pager:
        options:
          tags:
            next: 'Next ›'
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      filters:
        title:
          expose:
            label: ناونیشان
        type:
          expose:
            label: 'جۆری ناوەڕۆک'
        langcode:
          expose:
            label: زمان
  moderated_content:
    display_title: 'Moderated content'
