display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      arguments:
        uid:
          exception:
            title: هەموو
  block:
    display_title: بلۆک
