display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      fields:
        name:
          label: 'ناوی تێپەڕبوون'
        status:
          label: ڕەوش
          settings:
            format_custom_true: چالاکە
        roles_target_id:
          label: ڕۆڵەکان
        operations:
          label: کاره‌کان
      filters:
        status:
          group_info:
            label: ڕەوش
            group_items:
              1:
                title: چالاکە
  page_2:
    display_options:
      filters:
        status:
          group_info:
            label: ڕەوش
            group_items:
              1:
                title: چالاکە
