label: 'ناوەڕۆکە نوێیەکان'
display:
  default:
    display_title: Master
    display_options:
      title: 'ناوەڕۆکە نوێیەکان'
      exposed_form:
        options:
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      empty:
        area_text_custom:
          content: 'No content available.'
      use_more_text: زیاتر
  block_1:
    display_title: بلۆک
