label: 'Need Help View Ku'
display:
  default:
    display_options:
      title: 'Pêdiviya alîkariyê heye'
      fields:
        nothing:
          label: Navnîşan
        field_email_id:
          label: 'Nasnameya E-nameyê'
        field_telephone_number:
          label: 'Hejmara Telefonê'
        nothing_1:
          label: 'Medyaya civakî'
        field_service_provider_name:
          label: 'Navê Rêxistinê'
        field_description:
          label: Terîf
      header:
        area_text_custom:
          content: '<b>Hûn bajar ji welat hildibijêrin</b>'
      pager:
        options:
          tags:
            next: 'Piştî ›'
            previous: '‹ Pêşî'
            first: '« Yekem'
            last: 'Dawîn »'
