display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      fields:
        filename:
          label: ناو
        status:
          label: ڕەوش
      filters:
        status:
          expose:
            label: ڕەوش
  page_2:
    display_options:
      arguments:
        fid:
          exception:
            title: هەموو
