label: 'Sub Category All Result Kurdish'
display:
  default:
    display_options:
      header:
        result:
          content: 'HEMÛ ENCAM (@total)'
      empty:
        area:
          content:
            value: "<p>No naverok Berdest e</p>\r\n"
            format: basic_html
