display:
  default:
    display_title: Master
    display_options:
      title: 'ئەرشیڤی مانگانە'
      exposed_form:
        options:
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
  block_1:
    display_title: بلۆک
  page_1:
    display_title: پەڕە
