display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      fields:
        title:
          label: ناونیشان
        name:
          label: نووسەر
        changed:
          label: 'دواترین نوێبوونەوە'
  attachment_1:
    display_title: پاشکۆ
  page_1:
    display_title: پەڕە
