label: گەڕان
display:
  default:
    display_options:
      title: گەڕان
      use_more_text: 'Zêdetir Barkirin'
      header:
        result:
          content: 'هەموو ئەنجامەکان (@total)'
    display_title: گەڕان
