label: 'لاپەڕەی سەرەتا'
display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
    display_title: Master
  page_1:
    display_title: پەڕە
