label: 'بۆچوونە تازەکان'
display:
  default:
    display_title: Master
    display_options:
      title: 'بۆچوونە تازەکان'
      empty:
        area_text_custom:
          content: 'No comments available.'
  block_1:
    display_title: بلۆک
    display_options:
      block_description: 'بۆچوونە تازەکان'
