label: Files
display:
  default:
    display_title: Master
    display_options:
      title: Files
      fields:
        filename:
          label: ناو
        filesize:
          label: Size
        status:
          label: ڕەوش
        count:
          label: 'Used in'
      pager:
        options:
          tags:
            next: 'Next ›'
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      filters:
        filename:
          expose:
            label: Filename
        status:
          expose:
            label: ڕەوش
  page_1:
    display_options:
      menu:
        title: Files
  page_2:
    display_options:
      pager:
        options:
          tags:
            next: 'Next ›'
      arguments:
        fid:
          exception:
            title: هەموو
