label: 'لاپەڕەی سەرەتا'
display:
  default:
    display_title: Master
    display_options:
      pager:
        options:
          tags:
            next: 'Next ›'
      exposed_form:
        options:
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
  page_1:
    display_title: پەڕە
