display:
  default:
    display_title: Master
    display_options:
      title: 'کێ لەسەر هێڵە'
      exposed_form:
        options:
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
  who_s_online_block:
    display_title: 'کێ لەسەر هێڵە'
    display_options:
      block_description: 'کێ لەسەر هێڵە'
