display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      fields:
        filename:
          label: ناو
        status:
          label: ڕەوش
      filters:
        status:
          expose:
            label: ڕەوش
