display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      fields:
        nid:
          label: 'Count views'
  block:
    display_title: بلۆک
