label: 'بۆچوونە تازەکان'
display:
  default:
    display_title: Master
    display_options:
      title: 'بۆچوونە تازەکان'
  block_1:
    display_title: بلۆک
    display_options:
      block_description: 'بۆچوونە تازەکان'
