display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      fields:
        title:
          label: ناونیشان
  page:
    display_title: پەڕە
