display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      fields:
        node_bulk_form:
          action_title: کردار
        title:
          label: ناونیشان
        type:
          label: 'جۆری ناوەڕۆک'
        operations:
          label: کاره‌کان
      filters:
        status:
          group_info:
            group_items:
              1:
                title: بڵاوکراوەتەوە
        type:
          expose:
            label: 'جۆری ناوەڕۆک'
        title:
          expose:
            label: ناونیشان
  page_1:
    display_title: پەڕە
