display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Search
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      fields:
        type:
          label: جۆر
      filters:
        search_api_fulltext:
          expose:
            label: Search
      title: Search
  page:
    display_options:
      menu:
        title: Search
