label: 'ناوەڕۆکە نوێیەکان'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          reset_button_label: 'گەڕاندنەوە بۆ باری سەرەتایی'
      title: 'ناوەڕۆکە نوێیەکان'
      use_more_text: زیاتر
  block_1:
    display_title: بلۆک
