_core:
  default_config_hash: JqYNByWeXZGynyqoPRWQIjp3VcQhuoyq5WlM-7YzBvI
smtp_on: false
smtp_host: smtp.sendgrid.net
smtp_hostbackup: '25'
smtp_port: '587'
smtp_protocol: standard
smtp_autotls: true
smtp_timeout: 30
smtp_username: apikey
smtp_password: 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
smtp_from: nishtha.pradhan@qed42.com
smtp_fromname: ''
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: false
smtp_test_address: ''
smtp_reroute_address: ''
smtp_debugging: false
smtp_debug_level: 1
prev_mail_system: php_mail
smtp_keepalive: false
