<?php

/**
 * @file
 * Contains vss_common_config.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function vss_common_config_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the vss_common_config module.
    case 'help.page.vss_common_config':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module contains common configuration for the site.') . '</p>';
      return $output;

    default:
  }
}
